base: --no-source --color --format pretty
default: --profile qa
qa: --profile base PROFILE=qa
local: --profile base PROFILE=local
html_report: --format progress --format html --out=reports/features_report.html 
bvt: --tags @bvt